name: 'Scan github action'
description: 'A github action to scan repositories Dockerfile'
inputs:
  GH_TOKEN:
    description: 'A Github PAT'
    required: true

outputs:
  SEMGREP_CHECK:
    description: 'check of sempgre'
    value: ${{ steps.executing_action.outputs.SEMGREP_CHECK }}
  GITLEAKS_CHECK:
    description: 'check of gitleaks'
    value: ${{ steps.executing_action.outputs.GITLEAKS_CHECK }}
  TRIVY_SECRET_CHECK:
    description: 'check of trivy secret'
    value: ${{ steps.executing_action.outputs.TRIVY_SECRET_CHECK }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4 
      name: Setting python version
      with:
        python-version: 'pypy3.9'
        
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
      name: Installing dependencies
      
    - name: Executing action
      id: executing_action
      run: | 
        export GH_TOKEN=${{ inputs.GH_TOKEN }}
        python $GITHUB_ACTION_PATH/src/main.py
        echo "TRIVY_SECRET_CHECK=$TRIVY_SECRET_CHECK" >> $GITHUB_OUTPUT
        echo "GITLEAKS_CHECK=$GITLEAKS_CHECK" >> $GITHUB_OUTPUT
        echo "SEMGREP_CHECK=$SEMGREP_CHECK" >> $GITHUB_OUTPUT
      shell: bash
